apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
spec:
  replicas: {{ .Values.replicaCount }}  # Reference the replica count from values.yaml
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"  # Include the image tag
          ports:
            - containerPort: {{ .Values.frontend.service.port }}  # Correctly reference the service port
