apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  type: ClusterIP  # Change to LoadBalancer if you need external access
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
